# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=8, null=True)),
                ('long_url', models.URLField(max_length=254)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'url_map',
            },
        ),
    ]
